movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
  path('', views.index, name="index"),
  path('<movie_id>', views.detail, name="detail")
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MoviesResource
from . import views

movie_resource = MoviesResource()
urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# Create your models here.
class MoviesResource(ModelResource):
  class Meta:
    queryset = Movie.objects.all()
    resource_name = 'movies'
    # excludes = ['release_year']

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Gener(models.Model):
  name = models.CharField(max_length=255)
  def __str__(self):
    return self.name
  
class Movie(models.Model):
  title = models.CharField(max_length=255)
  release_year = models.IntegerField()
  number_in_stock = models.IntegerField()
  daily_rate = models.FloatField()
  gener = models.ForeignKey(Gener, on_delete=models.CASCADE)
  date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import  Movie


def index(request):
  movies = Movie.objects.all()
  # output = ', '.join([m.title for m in movies])
  # # SELECT * FROM movies_movie
  # Movie.objects.filter(release_year=1984)
  # # SELECT * FROM movies_movie WHERE release_year=1984
  # Movie.objects.get(id=1)
  # return HttpResponse(output)
  return render(request, 'movies/index.html', {'movies': movies})

def detail(request, movie_id):
  movie = get_object_or_404(Movie ,id=movie_id)
  return render(request, 'movies/detail.html', {'movie': movie})

   

vidly/views.py
from django.shortcuts import render

app_name = 'movies'
def home(request):
  return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <dl class="container">
    <dt>Title</dt>
    <dt>{{ movie.title }}</dt>
    <dt>Gener</dt>
    <dt>{{ movie.gener }}</dt>
    <dt>Stock</dt>
    <dt>{{ movie.number_in_stock }}</dt>
  </dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Gener</th>
        <th>Stock</th>
        <th>Daily Rate</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in movies %}
      <tr>
        <td class="text-primary link-underline-primary"><a class="text-decoration-none hover:text-underline" href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
        <td>{{ movie.gener }}</td>
        <td>{{ movie.number_in_stock }}</td>
        <td>{{ movie.daily_rate }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table> 
</main>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Vidly</title>
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Vidly</a>
    </div>
  </nav>
  {% block content %}
  {% endblock  %}
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <a href="{% url 'movies:index' %}" class="container">movies</a>
{% endblock %}